export const filterOptions = {
  roles: [
    'Software Engineer',
    'Frontend Developer',
    'Backend Developer',
    'Full Stack Developer',
    'Data Scientist',
    'Product Manager',
    'UI/UX Designer',
    'DevOps Engineer',
    'Business Analyst',
    'Digital Marketing Manager',
    'HR Manager',
    'Financial Analyst',
    'Sales Executive',
    'Content Writer',
    'Customer Support',
    'Quality Analyst',
    'Mobile Developer',
    'Cloud Architect',
    'Cybersecurity Analyst',
  ],
  locations: [
    'Bangalore',
    'Mumbai',
    'Delhi NCR',
    'Hyderabad',
    'Pune',
    'Chennai',
    'Kolkata',
    'Ahmedabad',
    'Jaipur',
    'Surat',
    'Remote',
    'Work From Home',
  ],
  experience: [
    'Fresher (0-1 years)',
    '1-3 years',
    '3-5 years',
    '5-8 years',
    '8-10 years',
    '10+ years',
  ],
  qualifications: [
    'B.Tech/B.E.',
    'M.Tech/M.E.',
    'MBA',
    'MCA',
    'BCA',
    'B.Sc',
    'M.Sc',
    'Any Graduate',
    'PhD',
  ],
  salaryRanges: [
    '0-3 LPA',
    '3-6 LPA',
    '6-10 LPA',
    '10-15 LPA',
    '15-25 LPA',
    '25-50 LPA',
    '50+ LPA',
  ],
  recruiterTypes: [
    'Startup',
    'MNC',
    'Corporate',
    'Government',
    'Non-Profit',
    'Agency',
  ],
};

export const jobsData = [
  {
    id: 1,
    title: 'Senior Frontend Developer',
    company: 'TechCorp Solutions',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '12-18 LPA',
    location: 'Bangalore',
    tags: ['Work From Home', 'Full Time', 'React', 'TypeScript'],
    postedDate: '2 days ago',
    applicants: 45,
  },
  {
    id: 2,
    title: 'Product Manager',
    company: 'InnovateTech Pvt Ltd',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '5-8 years',
    salary: '20-30 LPA',
    location: 'Mumbai',
    tags: ['Hybrid', 'Full Time', 'Product Strategy', 'Agile'],
    postedDate: '1 day ago',
    applicants: 78,
  },
  {
    id: 3,
    title: 'UI/UX Designer',
    company: 'DesignHub Studios',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '8-12 LPA',
    location: 'Pune',
    tags: ['Remote', 'Full Time', 'Figma', 'User Research'],
    postedDate: '3 days ago',
    applicants: 32,
  },
  {
    id: 4,
    title: 'Data Scientist',
    company: 'DataMinds Analytics',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '15-25 LPA',
    location: 'Hyderabad',
    tags: ['Work From Home', 'Full Time', 'Python', 'Machine Learning'],
    postedDate: '5 days ago',
    applicants: 56,
  },
  {
    id: 5,
    title: 'DevOps Engineer',
    company: 'CloudScale Inc',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '5-8 years',
    salary: '18-28 LPA',
    location: 'Bangalore',
    tags: ['Hybrid', 'Full Time', 'AWS', 'Kubernetes', 'Docker'],
    postedDate: '1 week ago',
    applicants: 41,
  },
  {
    id: 6,
    title: 'Full Stack Developer',
    company: 'WebWorks Solutions',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '10-16 LPA',
    location: 'Delhi NCR',
    tags: ['Remote', 'Full Time', 'MERN Stack', 'Node.js'],
    postedDate: '4 days ago',
    applicants: 67,
  },
  {
    id: 7,
    title: 'Backend Developer',
    company: 'CodeCraft Technologies',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '14-20 LPA',
    location: 'Chennai',
    tags: ['Work From Home', 'Full Time', 'Java', 'Spring Boot'],
    postedDate: '2 days ago',
    applicants: 53,
  },
  {
    id: 8,
    title: 'Digital Marketing Manager',
    company: 'GrowthHackers India',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '5-8 years',
    salary: '12-18 LPA',
    location: 'Mumbai',
    tags: ['Hybrid', 'Full Time', 'SEO', 'Content Marketing', 'Analytics'],
    postedDate: '1 day ago',
    applicants: 89,
  },
  {
    id: 9,
    title: 'HR Manager',
    company: 'TalentFirst Consulting',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '5-8 years',
    salary: '10-15 LPA',
    location: 'Pune',
    tags: ['Office', 'Full Time', 'Recruitment', 'Employee Relations'],
    postedDate: '3 days ago',
    applicants: 34,
  },
  {
    id: 10,
    title: 'Business Analyst',
    company: 'StrategyMinds Corp',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '11-16 LPA',
    location: 'Bangalore',
    tags: ['Hybrid', 'Full Time', 'SQL', 'Tableau', 'Business Intelligence'],
    postedDate: '6 days ago',
    applicants: 47,
  },
  {
    id: 11,
    title: 'Mobile Developer (Android)',
    company: 'AppGenius Studios',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '8-14 LPA',
    location: 'Hyderabad',
    tags: ['Remote', 'Full Time', 'Kotlin', 'Android SDK'],
    postedDate: '2 days ago',
    applicants: 62,
  },
  {
    id: 12,
    title: 'Quality Analyst',
    company: 'TestPro Solutions',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '5-9 LPA',
    location: 'Chennai',
    tags: ['Office', 'Full Time', 'Manual Testing', 'Automation'],
    postedDate: '5 days ago',
    applicants: 28,
  },
  {
    id: 13,
    title: 'Content Writer',
    company: 'WordSmith Media',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '4-7 LPA',
    location: 'Remote',
    tags: ['Work From Home', 'Full Time', 'SEO Writing', 'Blog Posts'],
    postedDate: '1 day ago',
    applicants: 91,
  },
  {
    id: 14,
    title: 'Financial Analyst',
    company: 'MoneyMatters Finance',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '9-14 LPA',
    location: 'Mumbai',
    tags: ['Office', 'Full Time', 'Excel', 'Financial Modeling'],
    postedDate: '4 days ago',
    applicants: 39,
  },
  {
    id: 15,
    title: 'Sales Executive',
    company: 'SalesForce India',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '3-6 LPA',
    location: 'Delhi NCR',
    tags: ['Office', 'Full Time', 'B2B Sales', 'Client Management'],
    postedDate: '2 days ago',
    applicants: 102,
  },
  {
    id: 16,
    title: 'Cloud Architect',
    company: 'SkyNet Cloud Services',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '8-10 years',
    salary: '30-45 LPA',
    location: 'Bangalore',
    tags: ['Hybrid', 'Full Time', 'AWS', 'Azure', 'GCP'],
    postedDate: '1 week ago',
    applicants: 23,
  },
  {
    id: 17,
    title: 'Cybersecurity Analyst',
    company: 'SecureGuard Technologies',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '13-19 LPA',
    location: 'Pune',
    tags: ['Work From Home', 'Full Time', 'Penetration Testing', 'Security'],
    postedDate: '3 days ago',
    applicants: 31,
  },
  {
    id: 18,
    title: 'Customer Support Executive',
    company: 'HelpDesk Pro',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '0-1 years',
    salary: '2-4 LPA',
    location: 'Kolkata',
    tags: ['Office', 'Full Time', 'Voice', 'Customer Service'],
    postedDate: '1 day ago',
    applicants: 145,
  },
  {
    id: 19,
    title: 'Data Engineer',
    company: 'BigData Solutions',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '14-22 LPA',
    location: 'Hyderabad',
    tags: ['Remote', 'Full Time', 'Spark', 'Hadoop', 'ETL'],
    postedDate: '6 days ago',
    applicants: 44,
  },
  {
    id: 20,
    title: 'Machine Learning Engineer',
    company: 'AI Innovations Lab',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '5-8 years',
    salary: '22-35 LPA',
    location: 'Bangalore',
    tags: ['Hybrid', 'Full Time', 'TensorFlow', 'PyTorch', 'NLP'],
    postedDate: '2 days ago',
    applicants: 38,
  },
  {
    id: 21,
    title: 'Junior Frontend Developer',
    company: 'WebCraft Studios',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '0-1 years',
    salary: '3-6 LPA',
    location: 'Chennai',
    tags: ['Office', 'Full Time', 'HTML', 'CSS', 'JavaScript'],
    postedDate: '1 day ago',
    applicants: 156,
  },
  {
    id: 22,
    title: 'Product Designer',
    company: 'PixelPerfect Design',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '10-16 LPA',
    location: 'Mumbai',
    tags: ['Remote', 'Full Time', 'Sketch', 'Figma', 'Prototyping'],
    postedDate: '4 days ago',
    applicants: 51,
  },
  {
    id: 23,
    title: 'SEO Specialist',
    company: 'RankFirst Digital',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '4-8 LPA',
    location: 'Pune',
    tags: ['Work From Home', 'Full Time', 'Google Analytics', 'SEO'],
    postedDate: '3 days ago',
    applicants: 73,
  },
  {
    id: 24,
    title: 'Java Developer',
    company: 'Enterprise Solutions Ltd',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '12-18 LPA',
    location: 'Delhi NCR',
    tags: ['Hybrid', 'Full Time', 'Java', 'Spring', 'Microservices'],
    postedDate: '5 days ago',
    applicants: 59,
  },
  {
    id: 25,
    title: 'Python Developer',
    company: 'CodePython Tech',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '7-12 LPA',
    location: 'Bangalore',
    tags: ['Remote', 'Full Time', 'Python', 'Django', 'Flask'],
    postedDate: '2 days ago',
    applicants: 82,
  },
  {
    id: 26,
    title: 'iOS Developer',
    company: 'AppleCraft Studios',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '13-20 LPA',
    location: 'Hyderabad',
    tags: ['Hybrid', 'Full Time', 'Swift', 'iOS SDK', 'SwiftUI'],
    postedDate: '1 week ago',
    applicants: 35,
  },
  {
    id: 27,
    title: 'Graphic Designer',
    company: 'CreativeMinds Agency',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '3-7 LPA',
    location: 'Jaipur',
    tags: ['Office', 'Full Time', 'Photoshop', 'Illustrator', 'Branding'],
    postedDate: '3 days ago',
    applicants: 94,
  },
  {
    id: 28,
    title: 'Operations Manager',
    company: 'LogiTech Operations',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '5-8 years',
    salary: '11-17 LPA',
    location: 'Mumbai',
    tags: ['Office', 'Full Time', 'Supply Chain', 'Process Optimization'],
    postedDate: '6 days ago',
    applicants: 42,
  },
  {
    id: 29,
    title: 'Blockchain Developer',
    company: 'CryptoChain Solutions',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '18-28 LPA',
    location: 'Bangalore',
    tags: ['Remote', 'Full Time', 'Solidity', 'Ethereum', 'Web3'],
    postedDate: '4 days ago',
    applicants: 27,
  },
  {
    id: 30,
    title: 'Social Media Manager',
    company: 'BuzzMedia Marketing',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '5-9 LPA',
    location: 'Delhi NCR',
    tags: ['Hybrid', 'Full Time', 'Instagram', 'Facebook', 'Content Strategy'],
    postedDate: '2 days ago',
    applicants: 118,
  },
  {
    id: 31,
    title: 'React Developer',
    company: 'ReactMasters Inc',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '8-14 LPA',
    location: 'Pune',
    tags: ['Work From Home', 'Full Time', 'React', 'Redux', 'JavaScript'],
    postedDate: '1 day ago',
    applicants: 97,
  },
  {
    id: 32,
    title: 'Angular Developer',
    company: 'AngularPro Solutions',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '11-17 LPA',
    location: 'Chennai',
    tags: ['Hybrid', 'Full Time', 'Angular', 'TypeScript', 'RxJS'],
    postedDate: '5 days ago',
    applicants: 48,
  },
  {
    id: 33,
    title: 'Vue.js Developer',
    company: 'VueExperts Tech',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '7-12 LPA',
    location: 'Bangalore',
    tags: ['Remote', 'Full Time', 'Vue.js', 'Nuxt', 'JavaScript'],
    postedDate: '3 days ago',
    applicants: 54,
  },
  {
    id: 34,
    title: 'Database Administrator',
    company: 'DataGuard Systems',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '5-8 years',
    salary: '15-22 LPA',
    location: 'Hyderabad',
    tags: ['Hybrid', 'Full Time', 'MySQL', 'PostgreSQL', 'MongoDB'],
    postedDate: '1 week ago',
    applicants: 29,
  },
  {
    id: 35,
    title: 'Network Engineer',
    company: 'NetWorks Solutions',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '9-14 LPA',
    location: 'Mumbai',
    tags: ['Office', 'Full Time', 'Cisco', 'Networking', 'Troubleshooting'],
    postedDate: '4 days ago',
    applicants: 36,
  },
  {
    id: 36,
    title: 'Technical Writer',
    company: 'DocuTech Communications',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '5-9 LPA',
    location: 'Remote',
    tags: ['Work From Home', 'Full Time', 'Documentation', 'API Docs'],
    postedDate: '2 days ago',
    applicants: 67,
  },
  {
    id: 37,
    title: 'Scrum Master',
    company: 'AgileWorks Consulting',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '5-8 years',
    salary: '14-20 LPA',
    location: 'Bangalore',
    tags: ['Hybrid', 'Full Time', 'Agile', 'Scrum', 'Jira'],
    postedDate: '6 days ago',
    applicants: 41,
  },
  {
    id: 38,
    title: 'AI Research Scientist',
    company: 'DeepMind Labs',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '8-10 years',
    salary: '35-55 LPA',
    location: 'Bangalore',
    tags: ['Hybrid', 'Full Time', 'Deep Learning', 'Research', 'Publications'],
    postedDate: '1 week ago',
    applicants: 18,
  },
  {
    id: 39,
    title: 'Flutter Developer',
    company: 'CrossPlatform Apps',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '6-11 LPA',
    location: 'Pune',
    tags: ['Remote', 'Full Time', 'Flutter', 'Dart', 'Mobile Apps'],
    postedDate: '3 days ago',
    applicants: 71,
  },
  {
    id: 40,
    title: 'Video Editor',
    company: 'MediaPro Studios',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '3-7 LPA',
    location: 'Mumbai',
    tags: ['Office', 'Full Time', 'Premiere Pro', 'After Effects'],
    postedDate: '2 days ago',
    applicants: 88,
  },
  {
    id: 41,
    title: 'Accountant',
    company: 'FinanceFirst Consultancy',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '5-9 LPA',
    location: 'Delhi NCR',
    tags: ['Office', 'Full Time', 'Tally', 'GST', 'Accounting'],
    postedDate: '5 days ago',
    applicants: 53,
  },
  {
    id: 42,
    title: 'Recruiter',
    company: 'HirePro Services',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '3-6 LPA',
    location: 'Bangalore',
    tags: ['Office', 'Full Time', 'Recruitment', 'Sourcing', 'Interviewing'],
    postedDate: '1 day ago',
    applicants: 124,
  },
  {
    id: 43,
    title: 'Legal Advisor',
    company: 'LegalEase Associates',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '5-8 years',
    salary: '12-18 LPA',
    location: 'Mumbai',
    tags: ['Office', 'Full Time', 'Corporate Law', 'Compliance'],
    postedDate: '1 week ago',
    applicants: 22,
  },
  {
    id: 44,
    title: 'Game Developer',
    company: 'GameZone Studios',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '10-16 LPA',
    location: 'Hyderabad',
    tags: ['Hybrid', 'Full Time', 'Unity', 'C#', 'Game Design'],
    postedDate: '4 days ago',
    applicants: 65,
  },
  {
    id: 45,
    title: 'Embedded Systems Engineer',
    company: 'IoTech Solutions',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '11-16 LPA',
    location: 'Bangalore',
    tags: ['Office', 'Full Time', 'C/C++', 'Embedded C', 'IoT'],
    postedDate: '6 days ago',
    applicants: 31,
  },
  {
    id: 46,
    title: 'Marketing Executive',
    company: 'BrandBoost Marketing',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '0-1 years',
    salary: '2-4 LPA',
    location: 'Jaipur',
    tags: ['Office', 'Full Time', 'Marketing', 'Lead Generation'],
    postedDate: '2 days ago',
    applicants: 134,
  },
  {
    id: 47,
    title: 'PHP Developer',
    company: 'WebDynamic Solutions',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '4-8 LPA',
    location: 'Chennai',
    tags: ['Remote', 'Full Time', 'PHP', 'Laravel', 'MySQL'],
    postedDate: '3 days ago',
    applicants: 76,
  },
  {
    id: 48,
    title: 'System Administrator',
    company: 'SysOps Technologies',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '8-13 LPA',
    location: 'Pune',
    tags: ['Office', 'Full Time', 'Linux', 'Windows Server', 'Networking'],
    postedDate: '5 days ago',
    applicants: 44,
  },
  {
    id: 49,
    title: 'Node.js Developer',
    company: 'BackendMasters Inc',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '12-19 LPA',
    location: 'Bangalore',
    tags: ['Work From Home', 'Full Time', 'Node.js', 'Express', 'MongoDB'],
    postedDate: '1 day ago',
    applicants: 83,
  },
  {
    id: 50,
    title: 'Automation Test Engineer',
    company: 'QualityFirst Testing',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '9-15 LPA',
    location: 'Hyderabad',
    tags: ['Hybrid', 'Full Time', 'Selenium', 'Java', 'TestNG'],
    postedDate: '4 days ago',
    applicants: 58,
  },
  {
    id: 51,
    title: 'Front End Architect',
    company: 'UIArchitects Corp',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '8-10 years',
    salary: '28-40 LPA',
    location: 'Mumbai',
    tags: ['Hybrid', 'Full Time', 'Architecture', 'React', 'Performance'],
    postedDate: '1 week ago',
    applicants: 19,
  },
  {
    id: 52,
    title: 'Salesforce Developer',
    company: 'CloudForce Solutions',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '13-20 LPA',
    location: 'Bangalore',
    tags: ['Remote', 'Full Time', 'Salesforce', 'Apex', 'Lightning'],
    postedDate: '3 days ago',
    applicants: 37,
  },
  {
    id: 53,
    title: 'Business Development Manager',
    company: 'GrowthVentures Ltd',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '5-8 years',
    salary: '15-25 LPA',
    location: 'Delhi NCR',
    tags: ['Office', 'Full Time', 'B2B', 'Partnerships', 'Strategy'],
    postedDate: '6 days ago',
    applicants: 49,
  },
  {
    id: 54,
    title: 'UX Researcher',
    company: 'UserFirst Research',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '11-17 LPA',
    location: 'Pune',
    tags: ['Hybrid', 'Full Time', 'User Research', 'Usability Testing'],
    postedDate: '2 days ago',
    applicants: 41,
  },
  {
    id: 55,
    title: 'SAP Consultant',
    company: 'EnterpriseSAP Services',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '5-8 years',
    salary: '18-28 LPA',
    location: 'Bangalore',
    tags: ['Hybrid', 'Full Time', 'SAP', 'ABAP', 'FICO'],
    postedDate: '1 week ago',
    applicants: 26,
  },
  {
    id: 56,
    title: 'Email Marketing Specialist',
    company: 'MailMasters Agency',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '4-8 LPA',
    location: 'Remote',
    tags: ['Work From Home', 'Full Time', 'Email Campaigns', 'Mailchimp'],
    postedDate: '3 days ago',
    applicants: 92,
  },
  {
    id: 57,
    title: 'Performance Marketing Manager',
    company: 'ROI Maximizers',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '5-8 years',
    salary: '16-24 LPA',
    location: 'Mumbai',
    tags: ['Hybrid', 'Full Time', 'Google Ads', 'Facebook Ads', 'Analytics'],
    postedDate: '5 days ago',
    applicants: 55,
  },
  {
    id: 58,
    title: 'Technical Support Engineer',
    company: 'SupportTech Solutions',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '3-6 LPA',
    location: 'Chennai',
    tags: ['Office', 'Full Time', 'Troubleshooting', 'Customer Support'],
    postedDate: '1 day ago',
    applicants: 107,
  },
  {
    id: 59,
    title: 'Penetration Tester',
    company: 'SecureHack Labs',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '14-22 LPA',
    location: 'Bangalore',
    tags: ['Remote', 'Full Time', 'Ethical Hacking', 'Security', 'VAPT'],
    postedDate: '4 days ago',
    applicants: 33,
  },
  {
    id: 60,
    title: 'Copywriter',
    company: 'WordCraft Agency',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '4-8 LPA',
    location: 'Mumbai',
    tags: ['Remote', 'Full Time', 'Creative Writing', 'Ad Copy'],
    postedDate: '2 days ago',
    applicants: 81,
  },
  {
    id: 61,
    title: 'Solutions Architect',
    company: 'TechSolutions Enterprise',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '8-10 years',
    salary: '32-48 LPA',
    location: 'Bangalore',
    tags: ['Hybrid', 'Full Time', 'Cloud', 'Architecture', 'Enterprise'],
    postedDate: '1 week ago',
    applicants: 21,
  },
  {
    id: 62,
    title: 'Data Analyst',
    company: 'InsightData Corp',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '6-11 LPA',
    location: 'Hyderabad',
    tags: ['Hybrid', 'Full Time', 'SQL', 'Excel', 'Power BI'],
    postedDate: '3 days ago',
    applicants: 96,
  },
  {
    id: 63,
    title: 'WordPress Developer',
    company: 'WebPress Studios',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '3-7 LPA',
    location: 'Pune',
    tags: ['Remote', 'Full Time', 'WordPress', 'PHP', 'WooCommerce'],
    postedDate: '5 days ago',
    applicants: 104,
  },
  {
    id: 64,
    title: 'Shopify Developer',
    company: 'EcomExperts Inc',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '5-10 LPA',
    location: 'Delhi NCR',
    tags: ['Work From Home', 'Full Time', 'Shopify', 'Liquid', 'E-commerce'],
    postedDate: '2 days ago',
    applicants: 68,
  },
  {
    id: 65,
    title: 'ERP Consultant',
    company: 'SystemsIntegration Ltd',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '5-8 years',
    salary: '15-23 LPA',
    location: 'Mumbai',
    tags: ['Office', 'Full Time', 'ERP', 'Implementation', 'Oracle'],
    postedDate: '1 week ago',
    applicants: 28,
  },
  {
    id: 66,
    title: 'Growth Hacker',
    company: 'StartupGrowth Labs',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '10-18 LPA',
    location: 'Bangalore',
    tags: ['Hybrid', 'Full Time', 'Growth Marketing', 'Analytics', 'A/B Testing'],
    postedDate: '4 days ago',
    applicants: 62,
  },
  {
    id: 67,
    title: 'Animator',
    company: 'AnimationPro Studios',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '4-8 LPA',
    location: 'Chennai',
    tags: ['Office', 'Full Time', '3D Animation', 'Maya', 'Blender'],
    postedDate: '6 days ago',
    applicants: 74,
  },
  {
    id: 68,
    title: 'Site Reliability Engineer',
    company: 'ReliableOps Inc',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '5-8 years',
    salary: '20-30 LPA',
    location: 'Bangalore',
    tags: ['Remote', 'Full Time', 'SRE', 'Monitoring', 'Incident Management'],
    postedDate: '3 days ago',
    applicants: 35,
  },
  {
    id: 69,
    title: 'Computer Vision Engineer',
    company: 'VisionAI Technologies',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '18-28 LPA',
    location: 'Hyderabad',
    tags: ['Hybrid', 'Full Time', 'OpenCV', 'Deep Learning', 'Image Processing'],
    postedDate: '1 week ago',
    applicants: 29,
  },
  {
    id: 70,
    title: 'Logistics Coordinator',
    company: 'SupplyChain Solutions',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '3-6 LPA',
    location: 'Pune',
    tags: ['Office', 'Full Time', 'Logistics', 'Coordination', 'Supply Chain'],
    postedDate: '2 days ago',
    applicants: 87,
  },
  {
    id: 71,
    title: 'Ruby on Rails Developer',
    company: 'RailsExperts Co',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '11-17 LPA',
    location: 'Bangalore',
    tags: ['Remote', 'Full Time', 'Ruby', 'Rails', 'PostgreSQL'],
    postedDate: '5 days ago',
    applicants: 42,
  },
  {
    id: 72,
    title: 'Go Developer',
    company: 'GolangPro Solutions',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '13-20 LPA',
    location: 'Hyderabad',
    tags: ['Work From Home', 'Full Time', 'Golang', 'Microservices', 'Docker'],
    postedDate: '4 days ago',
    applicants: 38,
  },
  {
    id: 73,
    title: 'Rust Developer',
    company: 'SystemLang Corp',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '5-8 years',
    salary: '18-28 LPA',
    location: 'Bangalore',
    tags: ['Remote', 'Full Time', 'Rust', 'Systems Programming', 'Performance'],
    postedDate: '1 week ago',
    applicants: 24,
  },
  {
    id: 74,
    title: 'Brand Manager',
    company: 'BrandBuilders Agency',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '5-8 years',
    salary: '14-22 LPA',
    location: 'Mumbai',
    tags: ['Office', 'Full Time', 'Branding', 'Marketing Strategy', 'Brand Identity'],
    postedDate: '6 days ago',
    applicants: 46,
  },
  {
    id: 75,
    title: 'AR/VR Developer',
    company: 'ImmersiveTech Labs',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '15-24 LPA',
    location: 'Bangalore',
    tags: ['Hybrid', 'Full Time', 'Unity', 'Unreal', 'AR', 'VR'],
    postedDate: '3 days ago',
    applicants: 31,
  },
  {
    id: 76,
    title: 'Compliance Officer',
    company: 'RegulatoryFirst Consulting',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '5-8 years',
    salary: '12-19 LPA',
    location: 'Delhi NCR',
    tags: ['Office', 'Full Time', 'Compliance', 'Risk Management', 'Regulatory'],
    postedDate: '1 week ago',
    applicants: 33,
  },
  {
    id: 77,
    title: 'Event Manager',
    company: 'EventPlanners Pro',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '6-11 LPA',
    location: 'Mumbai',
    tags: ['Office', 'Full Time', 'Event Planning', 'Coordination', 'Management'],
    postedDate: '4 days ago',
    applicants: 71,
  },
  {
    id: 78,
    title: 'Research Analyst',
    company: 'MarketResearch Insights',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '5-9 LPA',
    location: 'Bangalore',
    tags: ['Hybrid', 'Full Time', 'Research', 'Data Analysis', 'Reports'],
    postedDate: '2 days ago',
    applicants: 64,
  },
  {
    id: 79,
    title: 'Supply Chain Manager',
    company: 'LogisticsPro International',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '5-8 years',
    salary: '13-20 LPA',
    location: 'Chennai',
    tags: ['Office', 'Full Time', 'Supply Chain', 'Procurement', 'Logistics'],
    postedDate: '1 week ago',
    applicants: 38,
  },
  {
    id: 80,
    title: 'Kotlin Developer',
    company: 'AndroidMasters Inc',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '7-13 LPA',
    location: 'Pune',
    tags: ['Remote', 'Full Time', 'Kotlin', 'Android', 'Mobile Development'],
    postedDate: '3 days ago',
    applicants: 79,
  },
  {
    id: 81,
    title: 'TypeScript Developer',
    company: 'TypedCode Solutions',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '12-18 LPA',
    location: 'Bangalore',
    tags: ['Work From Home', 'Full Time', 'TypeScript', 'Node.js', 'React'],
    postedDate: '5 days ago',
    applicants: 57,
  },
  {
    id: 82,
    title: 'Insurance Sales Agent',
    company: 'SecureLife Insurance',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '0-1 years',
    salary: '2-5 LPA',
    location: 'Jaipur',
    tags: ['Office', 'Full Time', 'Sales', 'Insurance', 'Client Management'],
    postedDate: '1 day ago',
    applicants: 142,
  },
  {
    id: 83,
    title: 'Customer Success Manager',
    company: 'ClientFirst SaaS',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '10-16 LPA',
    location: 'Bangalore',
    tags: ['Hybrid', 'Full Time', 'Customer Success', 'SaaS', 'Account Management'],
    postedDate: '4 days ago',
    applicants: 52,
  },
  {
    id: 84,
    title: 'Interior Designer',
    company: 'SpaceDesign Studios',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '3-7 LPA',
    location: 'Mumbai',
    tags: ['Office', 'Full Time', 'Interior Design', '3ds Max', 'AutoCAD'],
    postedDate: '6 days ago',
    applicants: 83,
  },
  {
    id: 85,
    title: 'Talent Acquisition Specialist',
    company: 'RecruitmentExperts Inc',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '7-12 LPA',
    location: 'Pune',
    tags: ['Office', 'Full Time', 'Recruitment', 'Talent Acquisition', 'Sourcing'],
    postedDate: '2 days ago',
    applicants: 69,
  },
  {
    id: 86,
    title: 'Equity Research Analyst',
    company: 'InvestmentInsights Ltd',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '11-18 LPA',
    location: 'Mumbai',
    tags: ['Office', 'Full Time', 'Equity Research', 'Financial Analysis', 'CFA'],
    postedDate: '1 week ago',
    applicants: 34,
  },
  {
    id: 87,
    title: 'DevSecOps Engineer',
    company: 'SecureDevOps Solutions',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '5-8 years',
    salary: '19-29 LPA',
    location: 'Bangalore',
    tags: ['Remote', 'Full Time', 'DevSecOps', 'Security', 'CI/CD'],
    postedDate: '5 days ago',
    applicants: 27,
  },
  {
    id: 88,
    title: 'NLP Engineer',
    company: 'LanguageAI Labs',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '16-26 LPA',
    location: 'Hyderabad',
    tags: ['Hybrid', 'Full Time', 'NLP', 'Python', 'Machine Learning'],
    postedDate: '3 days ago',
    applicants: 41,
  },
  {
    id: 89,
    title: 'Motion Graphics Designer',
    company: 'AnimateThis Studio',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '4-9 LPA',
    location: 'Mumbai',
    tags: ['Hybrid', 'Full Time', 'After Effects', 'Motion Design', 'Animation'],
    postedDate: '4 days ago',
    applicants: 76,
  },
  {
    id: 90,
    title: 'Cloud Security Engineer',
    company: 'CloudGuard Technologies',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '5-8 years',
    salary: '18-28 LPA',
    location: 'Bangalore',
    tags: ['Remote', 'Full Time', 'Cloud Security', 'AWS', 'Azure Security'],
    postedDate: '1 week ago',
    applicants: 30,
  },
  {
    id: 91,
    title: 'Product Owner',
    company: 'AgilePro Solutions',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '5-8 years',
    salary: '17-26 LPA',
    location: 'Pune',
    tags: ['Hybrid', 'Full Time', 'Product Management', 'Agile', 'Scrum'],
    postedDate: '6 days ago',
    applicants: 44,
  },
  {
    id: 92,
    title: 'Telesales Executive',
    company: 'CallCenter Solutions',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '0-1 years',
    salary: '2-4 LPA',
    location: 'Delhi NCR',
    tags: ['Office', 'Full Time', 'Telesales', 'Voice', 'Sales'],
    postedDate: '1 day ago',
    applicants: 167,
  },
  {
    id: 93,
    title: 'Infrastructure Engineer',
    company: 'InfraTech Systems',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '11-17 LPA',
    location: 'Bangalore',
    tags: ['Office', 'Full Time', 'Infrastructure', 'Linux', 'Virtualization'],
    postedDate: '5 days ago',
    applicants: 39,
  },
  {
    id: 94,
    title: 'E-commerce Manager',
    company: 'OnlineRetail Corp',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '9-15 LPA',
    location: 'Mumbai',
    tags: ['Hybrid', 'Full Time', 'E-commerce', 'Marketplace', 'Operations'],
    postedDate: '3 days ago',
    applicants: 58,
  },
  {
    id: 95,
    title: 'Big Data Engineer',
    company: 'DataScale Solutions',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '5-8 years',
    salary: '18-27 LPA',
    location: 'Hyderabad',
    tags: ['Remote', 'Full Time', 'Hadoop', 'Spark', 'Big Data'],
    postedDate: '1 week ago',
    applicants: 32,
  },
  {
    id: 96,
    title: 'IT Project Manager',
    company: 'ProjectPro Consultancy',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '8-10 years',
    salary: '22-35 LPA',
    location: 'Bangalore',
    tags: ['Hybrid', 'Full Time', 'Project Management', 'PMP', 'Agile'],
    postedDate: '6 days ago',
    applicants: 28,
  },
  {
    id: 97,
    title: 'Radio Jockey',
    company: 'FM Radio Network',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '3-6 LPA',
    location: 'Mumbai',
    tags: ['Office', 'Full Time', 'Radio', 'Voice', 'Entertainment'],
    postedDate: '4 days ago',
    applicants: 112,
  },
  {
    id: 98,
    title: 'UI Developer',
    company: 'InterfacePro Studios',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '1-3 years',
    salary: '6-11 LPA',
    location: 'Pune',
    tags: ['Remote', 'Full Time', 'HTML', 'CSS', 'JavaScript', 'UI Design'],
    postedDate: '2 days ago',
    applicants: 85,
  },
  {
    id: 99,
    title: 'Conversion Rate Optimizer',
    company: 'OptimizeNow Agency',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '10-16 LPA',
    location: 'Bangalore',
    tags: ['Hybrid', 'Full Time', 'CRO', 'A/B Testing', 'Analytics'],
    postedDate: '5 days ago',
    applicants: 47,
  },
  {
    id: 100,
    title: 'Investment Analyst',
    company: 'WealthManagement Inc',
    companyLogo: 'https://via.placeholder.com/60',
    experience: '3-5 years',
    salary: '12-19 LPA',
    location: 'Mumbai',
    tags: ['Office', 'Full Time', 'Investment Analysis', 'Portfolio Management', 'Finance'],
    postedDate: '1 week ago',
    applicants: 36,
  }
];